name: driver
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  google_maps_flutter: ^1.0.6
  location: ^3.1.0
  flutter_polyline_points: ^0.2.4
  flutter_google_places: ^0.2.6
  google_maps_webservice: ^0.0.18
  permission_handler: ^5.0.1+1
  firebase_auth: 0.15.4
  cloud_firestore: 0.13.4
  firebase_core: 0.4.4
  firebase_database: ^3.1.6
  latlong: ^0.6.1
  geolocator: ^6.1.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/destination_map_marker.png
    - assets/driving_pin.png
